# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mergen Naidoo
description: "Hi I'm Mergen. I am an experienced Data Head specializing in Analytics, Data Engineering, Machine Learning, Data Science, Data Management, and Data Strategy. I have 17 Years of experience in Financial Services (Banking and Insurance). I am a strong analytical and strategic thinker with a passion for developing teams that unlock opportunities in data. 
I have built many teams with skills in Data Engineering, ML Engineering, Data Science, Business Intelligence, Product support in both South Africa and London. My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Tanzania"
resume_url: /docs/M_Naidoo_cv_August 2023.pdf
avatar_image: /img/IMG_1043.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mergen-naidoo-4b49a638/" # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

